
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000
server:
  port: 22222
spring:
  application:
    name: java-server
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
#    url: jdbc:mysql://127.0.0.1:3306/game0?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false&allowMultiQueries=true
#    username: root
#    password: 123456
    url: jdbc:mysql://202.194.14.120:3306/java_2_06?allowPublicKeyRetrieval=true&useSSL=false
    username: java_2_06
    password: JavaP206@

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jmx:
    enabled:false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
attach:
  folder: /teach-2025/
logging:
  config: classpath:loggback.xml

